export const SET_AUTH_STATUS_AUTHED = "AUTHORIZATION::SET_AUTH_STATUS_AUTHED";
export const SET_AUTH_STATUS_NOT_AUTHED = "AUTHORIZATION::SET_AUTH_STATUS_NOT_AUTHED";
export const AUTH_REQUEST = "AUTHORIZATION::AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTHORIZATION::AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTHORIZATION::AUTH_FAILURE";
export const AUTH_RESET = "AUTHORIZATION::AUTH_RESET";