export const GET_EXCHANGE_REQUEST = "EXCHANGE::GET_EXCHANGE_REQUEST";
export const GET_EXCHANGE_SUCCESS = "EXCHANGE::GET_EXCHANGE_SUCCESS";
export const GET_EXCHANGE_FAILURE = "EXCHANGE::GET_EXCHANGE_FAILURE";