export const HOME = "/"
export const CHATS = "/chats"
export const PROFILE = "/profile"
export const EXCHANGE = "/exchange"
export const API_URL = "https://ap.exchangerate.host/latest?base=RUB&symbols=USD,EUR"