export const HOME = "/";
export const CHATS = "/chats";
export const CHAT_ID = "/:chatId?";
export const PROFILE = "/profile";
export const EXCHANGE = "/exchange";
export const LOGIN = "/login";
export const LOGOUT = "/logout";
export const SIGNUP = "/signup";
export const API_URL = "https://api.exchangerate.host/latest?base=RUB&symbols=USD,EUR";